### ISSUE TITLE
Criar um quick access

### ISSUE THREAD

**Issue by elisonlins** [mdsbarbieri/dynamoToolsBox#6]
Possibilidade de configurar alguns endereços de componentes para rápido acesso.

![image](https://user-images.githubusercontent.com/30733932/29334309-5df7a9c2-81dd-11e7-9918-00e13006ba8b.png)

**Comment by mdsbarbieri** [comment]
É um boa funcionalidade, porém o complicado vai ser integrar entre todos os browser e achar uma forma que as urls cadastradas não sejam removidas de forma alguma do navegador. 
Mas fica o desafio!

**Comment by mdsbarbieri** [comment]
DONE, 

You must need add a new array on tampermonkey 

unsafeWindow.favorites = [
    'componentUrls'
];
